'use client';
import { FormEvent, useState } from 'react';
import { createTicket, sendChat, streamChat } from '@/lib/api';
type Msg = { role: 'customer' | 'agent'; text: string; ticket?: string | null };
function friendlyError(e: unknown){ const m=e instanceof Error?e.message:''; if(m.includes('429')) return 'Too many requests. Please wait a minute and retry.'; if(m.includes('422')) return 'Please check your message and try again.'; if(m.includes('Failed to fetch')) return 'Network error. Check your connection.'; return 'Server error. Please retry or request human support.'; }
export function ChatShell() {
  const [messages, setMessages] = useState<Msg[]>([{ role: 'agent', text: 'Hi, I am FinGuard. How can I help with your account or support request?' }]);
  const [input, setInput] = useState(''); const [conversationId, setConversationId] = useState<string>(); const [loading, setLoading] = useState(false); const [error, setError] = useState<string>();
  async function onSubmit(e: FormEvent) { e.preventDefault(); if (!input.trim() || loading) return; const text = input.trim(); setInput(''); setError(undefined); setMessages((m) => [...m, { role: 'customer', text }, { role:'agent', text:'' }]); setLoading(true);
    try { let draft=''; const res = await streamChat(text, conversationId, (delta)=>{ draft += delta; setMessages(m => m.map((msg,i)=> i===m.length-1 ? {...msg,text:draft} : msg)); }); setConversationId(res.conversation_id); setMessages((m) => m.map((msg,i)=> i===m.length-1 ? { role:'agent', text: `${res.message}${res.handoff_required ? ` A human specialist has been notified${res.ticket_id ? ` (ticket ${res.ticket_id.slice(0,8)})` : ''}.` : ''}`, ticket: res.ticket_id } : msg)); }
    catch (e) { try { const res = await sendChat(text, conversationId); setConversationId(res.conversation_id); setMessages((m) => m.map((msg,i)=> i===m.length-1 ? { role:'agent', text: res.message, ticket:res.ticket_id } : msg)); } catch (fallbackError) { const msg=friendlyError(fallbackError); setError(msg); setMessages((m) => m.map((item,i)=> i===m.length-1 ? { role:'agent', text: msg } : item)); }} finally { setLoading(false); }}
  async function createManualTicket(){ if(!conversationId || loading) return; setLoading(true); try { const t=await createTicket(conversationId, 'Customer requested manual support from chat UI'); setMessages(m=>[...m,{role:'agent',text:`I created support ticket ${t.id.slice(0,8)} for this conversation.`, ticket:t.id}]); } catch(e){ setError(friendlyError(e)); } finally { setLoading(false); }}
  return <section aria-label="Customer support chat" className="rounded-2xl border border-slate-800 bg-slate-900/70 p-4 shadow-xl"><div className="mb-4 flex items-center justify-between"><p className="text-sm text-slate-400">{conversationId ? `Conversation ${conversationId.slice(0,8)}` : 'New conversation'} · streaming SSE</p><button disabled={!conversationId || loading} onClick={createManualTicket} className="rounded-lg border border-slate-700 px-3 py-1 text-sm disabled:opacity-40" aria-label="Create support ticket">Create ticket</button></div><div role="log" aria-live="polite" aria-busy={loading} className="mb-4 h-96 space-y-3 overflow-y-auto rounded-xl bg-slate-950/70 p-4">{messages.map((m,i)=><div key={i} className={m.role==='agent'?'text-left':'text-right'}><span className={`inline-block max-w-[80%] rounded-2xl px-4 py-2 ${m.role==='agent'?'bg-slate-800':'bg-brand-600'}`}>{m.text || '…'}</span>{m.ticket && <p className="mt-1 text-xs text-blue-300">Ticket reference: {m.ticket}</p>}</div>)}{loading && <p className="text-sm text-slate-400">FinGuard is streaming a response…</p>}</div>{error && <p role="alert" className="mb-3 rounded-lg border border-red-800 bg-red-950 p-2 text-sm text-red-200">{error}</p>}<form onSubmit={onSubmit} className="flex gap-2"><label className="sr-only" htmlFor="chat-input">Support message</label><input id="chat-input" disabled={loading} className="flex-1 rounded-xl border border-slate-700 bg-slate-950 px-4 py-3 outline-none focus:border-brand-600 disabled:opacity-60" value={input} onChange={(e)=>setInput(e.target.value)} placeholder="Ask about a transaction, card, dispute, or account issue"/><button disabled={loading || !input.trim()} className="rounded-xl bg-brand-600 px-5 py-3 font-semibold hover:bg-blue-500 disabled:opacity-50">{loading ? 'Sending…' : 'Send'}</button></form></section>;
}
